//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FITNESEntities : DbContext
    {
        public FITNESEntities()
            : base("name=FITNESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Dzien> Dziens { get; set; }
        public virtual DbSet<Harmonogram> Harmonograms { get; set; }
        public virtual DbSet<Klient> Klients { get; set; }
        public virtual DbSet<Przywileje> Przywilejes { get; set; }
        public virtual DbSet<Recepcja> Recepcjas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Trener> Treners { get; set; }
        public virtual DbSet<Trening> Trenings { get; set; }
        public virtual DbSet<Wywiad> Wywiads { get; set; }
        public virtual DbSet<Zajecia> Zajecias { get; set; }
        public virtual DbSet<Zdjecie> Zdjecies { get; set; }
    }
}
