//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Harmonogram
    {
        public int IdHarmonogramu { get; set; }
        public Nullable<int> IdDzien { get; set; }
        public Nullable<int> IdTrener { get; set; }
        public Nullable<System.DateTime> GodzinaRozpoczecia { get; set; }
        public Nullable<System.DateTime> GodzinaZakonczenia { get; set; }
    
        public virtual Dzien Dzien { get; set; }
        public virtual Trener Trener { get; set; }
    }
}
