//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trening
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trening()
        {
            this.Zajecias = new HashSet<Zajecia>();
        }
    
        public int IdTrening { get; set; }
        public Nullable<int> IdTrener { get; set; }
        public Nullable<int> IdKlient { get; set; }
        public Nullable<System.DateTime> DataGodzRozp { get; set; }
        public Nullable<System.DateTime> DataGodzZak { get; set; }
        public Nullable<bool> CzyZakonczony { get; set; }
        public decimal Kwota { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Trener Trener { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zajecia> Zajecias { get; set; }
    }
}
