//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wywiad
    {
        public int IdWywiad { get; set; }
        public Nullable<int> IdKlient { get; set; }
        public Nullable<bool> WadaSerca { get; set; }
        public Nullable<bool> Nadcisnienie { get; set; }
        public Nullable<bool> ZabRytmuSerca { get; set; }
        public Nullable<bool> Epilepsja { get; set; }
        public Nullable<bool> Alergia { get; set; }
        public Nullable<bool> Astma { get; set; }
        public Nullable<bool> Cukrzyca { get; set; }
        public string InneChoroby { get; set; }
    
        public virtual Klient Klient { get; set; }
    }
}
