//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zajecia
    {
        public int IdZajecia { get; set; }
        public Nullable<int> IdTrening { get; set; }
        public string NazwaZajec { get; set; }
        public string TypZajec { get; set; }
    
        public virtual Trening Trening { get; set; }
    }
}
