//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hercules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zdjecie
    {
        public int IdZdjecie { get; set; }
        public Nullable<int> IdKlient { get; set; }
        public byte[] Zdjecie1 { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Klient Klient { get; set; }
    }
}
